### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by medz** [odroe/odroe#17]
# oref

- #19
- [x] Support Stream to Derived/Ref
- [x] Observer

# DevTools

- [ ] Support `oinject` DevTools extension
- [ ] Support `oref` DevTools extension
- [ ] Support `oref_flutter` DevTools extension

**Comment by medz** [comment]
> # oref
> * [ ]  Support reactive `Map`
> * [ ]  Support reactive `List`
> * [ ]  Support reactive `Set`
> * [ ]  Support reactive `Iterable`
> * [ ]  Support Stream to Derived/Ref
> * [ ]  Observer
> 
> # DevTools
> * [ ]  Support `oinject` DevTools extension
> * [ ]  Support `oref` DevTools extension
> * [ ]  Support `oref_flutter` DevTools extension
